name: Deploy to Neocities
env:
  FORCE_COLOR: 1
  NODE_VERSION: lts/*
concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      # make sure your branch name matches! (ie. main, master, etc)
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
        # this will use the latest LTS version of Node.js
        # if you need a specific version, replace ${{ env.NODE_VERSION }} with that version number
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
        
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        # caches dependencies and other commonly re-used files
        # so they do not need to be re-installed on each run
        
      - name: Install dependencies and build site
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
        
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@master
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: dist
        # if dist_dir is within a subfolder, update the filepath to reflect that
